# Generated by Django 5.0.1 on 2024-01-26 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 26, 10, 21, 24, 949145))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
